User.create!([
  {email: "a@a.com", encrypted_password: "$2a$10$WlQ4NFQWvTPt2.eFqiDJmeKJemHJpyDy/grdltw3p1OkicK.jeSU.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-11-15 10:48:12", last_sign_in_at: "2014-11-15 10:44:00", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "A A"},
  {email: "b@b.com", encrypted_password: "$2a$10$k95YJ5YtZB/39PsmjBnFLuMyiDhNXaSPN.PcOkLTjqhOh9375Rr7e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-11-15 10:44:58", last_sign_in_at: "2014-11-15 10:44:39", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "B B"},
  {email: "c@c.com", encrypted_password: "$2a$10$WFRnbgiUPBmFDQwzuHpWauLDAq.fVLSmegytgOevTi.pd1cfH2CaC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-11-15 11:54:49", last_sign_in_at: "2014-11-15 10:45:30", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "C C"},
  {email: "d@d.com", encrypted_password: "$2a$10$3tmsHPXhkn5EroTzsP8G6es7Y6pzpY5NaCvIrj2JDGL0ZPI3uqe4O", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2014-11-15 10:46:05", last_sign_in_at: "2014-11-15 10:41:02", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "D D"},
  {email: "e@e.com", encrypted_password: "$2a$10$8amS1s3X1bXl2oSmi1ex6ul7b8MdXf8gf1GxCG8MUrIYk.2F5xvCS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2014-11-15 10:46:44", last_sign_in_at: "2014-11-15 10:41:36", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "E E"},
  {email: "f@f.com", encrypted_password: "$2a$10$IgPj9REqDEMWesoX3273Z.uQLyZ0Zp3Wbwx.2cGri6vqwdiv19Lve", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2014-11-15 10:42:07", last_sign_in_at: "2014-11-15 10:38:13", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "F F"}
])
Image.create!([
  {filename: "ZE0p0TN-1jMe2njTN8y8xQ.jpg", public: true, user_id: 6},
  {filename: "8AYUaAk-q8R9u-pu5UVcRQ.jpg", public: true, user_id: 6},
  {filename: "x6O1WKRUI3D0b_VlkOiX9Q.jpg", public: true, user_id: 6},
  {filename: "kpVulv-TL4QI3HvfVszETg.jpg", public: false, user_id: 6},
  {filename: "Ejg-L_JOaaf_K_uE1ipCEg.jpg", public: false, user_id: 6},
  {filename: "DQVMOd8VkdvPFYxzyb-oLg.jpg", public: false, user_id: 6},
  {filename: "-_w27nDLg8AZDuHXkQnS0g.jpg", public: false, user_id: 6},
  {filename: "Bw3J5EY6i57e_5P3VwZKew.jpg", public: false, user_id: 6},
  {filename: "lhtuQuBh_4y8IHIc9nclWw.jpg", public: false, user_id: 6},
  {filename: "4njnsIrnoX3xgdZBZlbXBg.jpg", public: false, user_id: 6},
  {filename: "4YdKFS4cM2tbvhAB1xP04g.jpg", public: false, user_id: 1},
  {filename: "ZQvl_COuD0zj7X8Ilb0NwA.jpg", public: true, user_id: 1},
  {filename: "sut2-2bqh2qEsCTaWnDMTg.jpg", public: true, user_id: 1},
  {filename: "H_bjY-TKftU-UsdIIjMJng.jpg", public: true, user_id: 1},
  {filename: "HsRXOJ_BAFAFS5MLFqgfDg.jpg", public: false, user_id: 1},
  {filename: "AFO8Jt-1h9MljdJ-DtubSQ.jpg", public: false, user_id: 1},
  {filename: "9tflUQ-CJ9TvwyrUcDP0oQ.jpg", public: false, user_id: 1},
  {filename: "Ckj-lYfiz6qqJqbEXd9MRg.jpg", public: false, user_id: 1},
  {filename: "55T4sri_GHA2d-JH31b_2A.jpg", public: false, user_id: 1},
  {filename: "a7lpXAI6XX1-lasjXDaMAw.jpg", public: false, user_id: 1},
  {filename: "QH9xUxEk94ppEhc5dUnFrQ.jpg", public: true, user_id: 2},
  {filename: "kgqtOdHU_JRhOmd8Zt_JLA.jpg", public: true, user_id: 2},
  {filename: "j7FFhTsUH82FJjuKL1aa6Q.jpg", public: false, user_id: 2},
  {filename: "yNHxVET5TRpXXObehYf-fA.jpg", public: false, user_id: 2},
  {filename: "hbgOQ_9Bpf7MfktRhCoG4A.jpg", public: false, user_id: 2},
  {filename: "Nxh9NTKBfWx3lnc8xFFZaw.jpg", public: false, user_id: 2},
  {filename: "-cp4c0F-O1ZLBc-Cyyp6uA.jpg", public: false, user_id: 2},
  {filename: "d44EJQsJpxlh7WbGgc9LYQ.jpg", public: false, user_id: 2},
  {filename: "wm7iU3LLlA4SVdNO8qnL6Q.jpg", public: false, user_id: 2},
  {filename: "M9kLNrnXYw09SU_kdGXjug.jpg", public: true, user_id: 3},
  {filename: "FGtL-d6-9WsqxmZ4nOtYog.jpg", public: true, user_id: 3},
  {filename: "BxAfNBMRR-Ezxaj3ZURC7Q.jpg", public: false, user_id: 3},
  {filename: "G1RcPrV_6LwFcRYMFdgv6g.jpg", public: false, user_id: 3},
  {filename: "XSbAzkYNKel06gCW5bBlUg.jpg", public: false, user_id: 3},
  {filename: "U33m5l3MEfbd5v55zLCiGA.jpg", public: false, user_id: 3},
  {filename: "crQL-tcYGGBYOHAd4sUidA.jpg", public: false, user_id: 3},
  {filename: "te6F47JsICimeSaZ1VbcgA.jpg", public: false, user_id: 3},
  {filename: "V_NUlnhSP7IoMF6CeoWosg.jpg", public: false, user_id: 3},
  {filename: "VbNv7QanFuExHOSAsUHbtQ.jpg", public: true, user_id: 4},
  {filename: "h4IWZYjKvi1-zTsifJw4jA.jpg", public: true, user_id: 4},
  {filename: "llQjcE9pDblIRtZ8wHdoaw.jpg", public: false, user_id: 4},
  {filename: "Fm41jOXtn3KngMV-A2qIRQ.jpg", public: false, user_id: 4},
  {filename: "YVbr2gp16zTMyJnHo97T3A.jpg", public: false, user_id: 4},
  {filename: "jaWmq7kyak8VboqMAaCywg.jpg", public: false, user_id: 4},
  {filename: "L6b1XzdNuO8ankX1HnZyew.jpg", public: false, user_id: 4},
  {filename: "V1CQMn1ivY0uFzMbJYXK6Q.jpg", public: false, user_id: 4},
  {filename: "a7YQogWUzFX6J7jaNDJZng.jpg", public: false, user_id: 4},
  {filename: "8dfZLamkeYWVShfHcpSjhQ.jpg", public: true, user_id: 5},
  {filename: "Af_qbGlQQYPlw32Bjd0OEQ.jpg", public: true, user_id: 5},
  {filename: "rk2Yb2wEeJHEvgL6V9qJbw.jpg", public: false, user_id: 5},
  {filename: "-z6EowL7s8qKoQuzQhvVZQ.jpg", public: false, user_id: 5},
  {filename: "bfFr1Eo-SD4e02hySJNkFA.jpg", public: false, user_id: 5},
  {filename: "U7PoKEGWI_-Ej-I955aZAQ.jpg", public: false, user_id: 5}
])
Imageuser.create!([
  {user_id: 1, image_id: 6},
  {user_id: 2, image_id: 6},
  {user_id: 3, image_id: 18},
  {user_id: 4, image_id: 18},
  {user_id: 5, image_id: 30},
  {user_id: 6, image_id: 30},
  {user_id: 6, image_id: 33},
  {user_id: 1, image_id: 33},
  {user_id: 2, image_id: 46},
  {user_id: 3, image_id: 46},
  {user_id: 3, image_id: 54},
  {user_id: 4, image_id: 54},
  {user_id: 3, image_id: 8},
  {user_id: 4, image_id: 8},
  {user_id: 1, image_id: 8},
  {user_id: 2, image_id: 8},
  {user_id: 1, image_id: 8},
  {user_id: 5, image_id: 8},
  {user_id: 2, image_id: 18},
  {user_id: 5, image_id: 18},
  {user_id: 6, image_id: 18},
  {user_id: 1, image_id: 29},
  {user_id: 3, image_id: 29},
  {user_id: 4, image_id: 29},
  {user_id: 5, image_id: 29},
  {user_id: 6, image_id: 29},
  {user_id: 2, image_id: 33},
  {user_id: 4, image_id: 33},
  {user_id: 5, image_id: 33},
  {user_id: 1, image_id: 43},
  {user_id: 2, image_id: 43},
  {user_id: 3, image_id: 43},
  {user_id: 5, image_id: 43},
  {user_id: 6, image_id: 43},
  {user_id: 1, image_id: 56},
  {user_id: 2, image_id: 56},
  {user_id: 3, image_id: 56},
  {user_id: 4, image_id: 56},
  {user_id: 6, image_id: 56},
  {user_id: 1, image_id: 37},
  {user_id: 4, image_id: 37},
  {user_id: 6, image_id: 37}
])
Tag.create!([
  {msg: "Tag from F", image_id: 8},
  {msg: "Tag from A", image_id: 18},
  {msg: "Tag from B", image_id: 29},
  {msg: "Tag from C", image_id: 33},
  {msg: "Tag from D", image_id: 43},
  {msg: "Tag from  E", image_id: 56},
  {msg: "Tag from C", image_id: 43},
  {msg: "Another tag from C", image_id: 43}
])
